blueprint:
  name: 👤✨ Person Detected Light Control (Grouped, Optional)
  description: >
    🔔 Triggers when a person is detected and it's within the active time window (default: sunset to sunrise).
    💡 Turns on selected groups of lights (porch, front yard, driveway) if they are off.
    ⏲️ Each group has its own auto-off delay.
    ✅ You can enable or disable each group independently.
    🕒 The active time window is configurable.
    🚫 Cooldown prevents overlapping triggers.

  domain: automation
  input:
    sensors:
      name: 👤 Person Detection Sensors
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    start_time:
      name: 🕒 Start Time
      description: Time after which automation can run (default: sunset)
      default: sunset
      selector:
        time: {}

    end_time:
      name: 🕒 End Time
      description: Time before which automation can run (default: sunrise)
      default: sunrise
      selector:
        time: {}

    use_porch:
      name: 🔆 Enable Porch Group
      default: true
      selector:
        boolean: {}

    porch_lights:
      name: Porch Lights
      selector:
        entity:
          domain: light
          multiple: true
    porch_delay:
      name: ⏱️ Porch Auto-Off Delay
      default: "00:05:00"
      selector:
        duration: {}

    use_front_yard:
      name: 🌼 Enable Front Yard Group
      default: true
      selector:
        boolean: {}

    front_yard_lights:
      name: Front Yard Lights
      selector:
        entity:
          domain: light
          multiple: true
    front_yard_delay:
      name: ⏱️ Front Yard Auto-Off Delay
      default: "00:07:00"
      selector:
        duration: {}

    use_driveway:
      name: 🚗 Enable Driveway Group
      default: true
      selector:
        boolean: {}

    driveway_lights:
      name: Driveway Lights
      selector:
        entity:
          domain: light
          multiple: true
    driveway_delay:
      name: ⏱️ Driveway Auto-Off Delay
      default: "00:05:00"
      selector:
        duration: {}

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input sensors
    to: "on"
    for: "00:00:05"

condition:
  - condition: time
    after: !input start_time
    before: !input end_time

variables:
  light_groups: >
    {% set groups = [] %}
    {% if (use_porch | default(true)) %}
      {% set _ = groups.append({'lights': porch_lights, 'delay': porch_delay}) %}
    {% endif %}
    {% if (use_front_yard | default(true)) %}
      {% set _ = groups.append({'lights': front_yard_lights, 'delay': front_yard_delay}) %}
    {% endif %}
    {% if (use_driveway | default(true)) %}
      {% set _ = groups.append({'lights': driveway_lights, 'delay': driveway_delay}) %}
    {% endif %}
    {{ groups }}

action:
  - repeat:
      for_each: "{{ light_groups }}"
      sequence:
        - repeat:
            for_each: "{{ repeat.item.lights }}"
            sequence:
              - condition: state
                entity_id: "{{ repeat.item }}"
                state: "off"
              - service: light.turn_on
                target:
                  entity_id: "{{ repeat.item }}"
              - delay: "{{ repeat.item.delay }}"
              - condition: state
                entity_id: "{{ repeat.item }}"
                state: "on"
              - service: light.turn_off
                target:
                  entity_id: "{{ repeat.item }}"
