blueprint:
  name: "👤✨ Person Detected Light Control (v3.1.1)"
  description: >
    📦 Version: 3.1.1
    🔔 Triggers when a person is detected between sunset and sunrise.
    💡 Turns on specified lights if they are off.
    ⏲️ Turns off lights after a specified delay.

  domain: automation
  input:
    sensors:
      name: "👤 Person Detection Sensors"
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    lights:
      name: "💡 Lights to Control"
      selector:
        entity:
          domain: light
          multiple: true

    delay:
      name: "⏱️ Off Delay"
      description: Duration to wait before turning off the lights.
      default: "00:05:00"
      selector:
        duration: {}

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input sensors
    to: "on"

condition:
  - condition: sun
    after: sunset
    before: sunrise

action:
  - service: light.turn_on
    target:
      entity_id: !input lights

  - delay: !input delay

  - service: light.turn_off
    target:
      entity_id: !input lights

