blueprint:
  name: "👤✨ Person Detected Light Control (Flexible)"
  description: >
    📦 Version: 2.0.0
    🔔 When a person is detected and it's nighttime (sunset to sunrise),
    this automation turns on one or more lights if they are off,
    waits a custom delay per light, and then turns them off if still on.

  domain: automation
  input:
    sensors:
      name: "👤 Person Detection Sensors"
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    lights:
      name: "💡 Lights to Control"
      selector:
        entity:
          domain: light
          multiple: true

    delays:
      name: "⏱️ Off Delays (one per light)"
      description: List of durations matching each light (e.g., ['00:05:00', '00:07:00'])
      default: []
      selector:
        object: {}

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input sensors
    to: "on"
    for: "00:00:05"

condition:
  - condition: sun
    after: sunset
    before: sunrise

action:
  - variables:
      light_list: !input lights
      delay_list: !input delays

  - repeat:
      for_each: "{{ range(0, light_list | length) }}"
      sequence:
        - variables:
            light: "{{ light_list[repeat.index] }}"
            delay: "{{ delay_list[repeat.index] | default('00:05:00') }}"
        - condition: state
          target:
            entity_id: "{{ light }}"
          state: "off"
        - service: light.turn_on
          target:
            target:
            entity_id: "{{ light }}"
        - delay: "{{ delay }}"
        - condition: state
          target:
            entity_id: "{{ light }}"
          state: "on"
        - service: light.turn_off
          target:
            target:
            entity_id: "{{ light }}"
